#:schema node_modules/wrangler/config-schema.json
name = "clima-agora-ia"
compatibility_date = "2024-03-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[vars]
# Variáveis de ambiente padrão para o deploy no Cloudflare Pages
NODE_VERSION = "20"
# Adicione a sua GEMINI_API_KEY no painel do Cloudflare (Secrets)
